
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           USERS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX


-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           CARS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX


-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           DRIVERS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX


-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           TRANSACTIONS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX


-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           TRIPS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX


-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           LOCATIONS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX


-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
--           REFUNDS
-- XXXXXXXXXXXXXXXXXXXXXXXXXXX
