# Generated by Django 4.1 on 2022-08-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CONVERTABLE', 'Convertable'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'Van')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_check', models.CharField(max_length=255)),
                ('profile_photo', models.CharField(max_length=255)),
                ('driver_license', models.CharField(max_length=255)),
                ('vehicle_insurance', models.CharField(max_length=255)),
                ('vehicle_registration', models.CharField(max_length=255)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CARD', max_length=255)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('surge_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.driver')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=24)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CARD', max_length=255)),
                ('is_driver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('trip_start_time', models.DateTimeField()),
                ('trip_end_time', models.DateTimeField()),
                ('trip_wait_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.driver')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.transaction')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.driver')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_name', models.CharField(max_length=255)),
                ('start_latitude', models.CharField(max_length=255)),
                ('start_longitude', models.CharField(max_length=255)),
                ('end_name', models.CharField(max_length=255)),
                ('end_latitude', models.CharField(max_length=255)),
                ('end_longitude', models.CharField(max_length=255)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.trip')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.driver'),
        ),
    ]
