# Generated by Django 4.1 on 2022-08-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver_id',
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('CONVERTABLE', 'Convertable'), ('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('VAN', 'Van')], max_length=255),
        ),
    ]
